config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :registrations => "user/registrations" }

  devise_scope :user do
    authenticated :user do
      root 'posts#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  # devise_scope :user do
  #   root to: "devise/sessions#new"
  # end

  # generate index for users
  # NOTE: put this after the 'devise_for :users' line
  resources :users, only: [:index, :show]
  resources :follows
  resources :posts

  get 'following', to: 'users#following'
  get 'find_people', to: 'users#find_people'
  get 'search_users', to: 'users#search'
  post 'follow_user', to: 'users#follow_user'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :user
  belongs_to :following, :class_name => 'User'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" } # default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  validates :image_file_name, presence: true
  validates :description, presence: true, length: { minimum: 5, maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy

  has_many :follows
  has_many :following, through: :follows

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, 
         # Tell Devise to use :login in the authentication_keys
         :authentication_keys => [:login]

  # add validation to check format of username to not allow @ character
  VALID_USERNAME_REGEX = /\A[a-zA-Z0-9_\.]*\z/
  validates :username, presence: true, 
            uniqueness: { case_sensitive: false }, 
            length: { minimum: 3, maximum: 25 },
            format: { with: VALID_USERNAME_REGEX }

  # to even more secure for the validation above
  validate :validate_username
  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end
  
  # Create a login virtual attribute in the User model
  attr_writer :login

  def login
    @login || self.username || self.email
  end

  # Overwrite Devise's find_for_database_authentication method in User model
  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

  # methods for searching user
  def self.search(param)
    param.strip!
    param.downcase!
    to_send_back = (username_matches(param) + email_matches(param)).uniq
    return nil unless to_send_back
    to_send_back
  end

  def self.username_matches(param)
    matches('username', param)
  end

  def self.email_matches(param)
    matches('email', param)
  end

  def self.matches(field_name, param)
    User.where("#{field_name} like?", "%#{param}%")
  end

  def except_current_user(users)
    users.reject { |user| user.id == self.id }
  end

  def not_follow_myself(user)
    user.id != self.id
  end

  # use this now in _result.html.erb
  # prevent to add already following
  def not_following_with?(following_id)
    follows.where(following_id: following_id).count < 1
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  def destroy
    @following = User.find(params[:id])
    @follow = current_user.follows.where(following_id: @following.id).first
    @follow.destroy
    flash[:success] = "Successfully unfollowed #{@following.username}"
    redirect_to user_path(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :require_same_user, only: [:destroy]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def show
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      flash[:success] = "Photo successfully uploaded"
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end

  def destroy
    @post.destroy
    flash[:success] = "Photo successfully deleted"
    redirect_to user_path(current_user)
  end

  private 

    def post_params 
      params.require(:post).permit(:image, :description)
    end

    def find_post
      @post = Post.find(params[:id])
    end

    def require_same_user
      if current_user != @post.user
        flash[:danger] = "You can only delete your own photo"
        redirect_to authenticated_root_url
      end
    end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password, :password_confirmation])
      devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email, :password, :password_confirmation])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :find_people, :search]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def following
    @follows = current_user.following
  end

  def search
    if params[:search_param].blank?
      flash.now[:danger] = "You have entered an empty search string"
    else
      @users = User.search(params[:search_param])
      if user_signed_in? && current_user
        @users = current_user.except_current_user(@users)
      end
      flash.now[:danger] = "No users match this search criteria" if @users.blank?
    end
    respond_to do |format|
      format.js { render partial: 'users/result' }
    end
  end

  def follow_user
    @following = User.find(params[:following])

    current_user.follows.build(following_id: @following.id)

    if current_user.save
      flash[:success] = "Successfully followed #{@following.username ? @following.username : @following.email}"
    else
      flash[:danger] = "There was something wrong on following the user, please update your username"
    end
    redirect_to user_path(@following)
  end

  def find_people
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
 def gravatar_for(user, option, design)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = option
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.email, class: design)
  end
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_error_messages.html.erb
<% if obj.errors.any? %>
  <div id="form-error">
    <div class="alert alert-danger alert-dismissable mx-auto">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <p><strong>This form contains <%= pluralize(obj.errors.count, 'error') %>.</strong></p>
      <ul>
        <% obj.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      Copyright &copy; Mark Hermano 2018, All Rights Reserved
    </small>
    <nav>
      <ul>
        <li><a href="https://hermanomark.github.io/" target="_blank">About</a></li>
      <ul>
    </nav>
  </footer>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark fixed-top">
  <div class="container">
    <!-- <a class="navbar-brand" href="#">Start Bootstrap</a> -->
    <%= link_to "<i class='fa fa-instagram' style='font-size:28px;color:white'></i> &nbsp; Instagramark".html_safe, posts_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Actions
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%- if user_signed_in? && current_user %>
              <%= link_to "New Post", new_post_path, class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
            <% end %>
              <%= link_to "<i class='fa fa-search'></i> &nbsp; Find People".html_safe, find_people_path, class: "dropdown-item" %>
          </div>
        </li>
    </ul>

      <ul class="navbar-nav ml-auto">
        <%- if user_signed_in? && current_user %>
        <li class="nav-item">
          <%= link_to "<i class='fa fa-user' style='font-size:24px'></i>".html_safe, user_path(current_user), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Following", following_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Home", authenticated_root_url, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Edit Account", edit_user_registration_path, class: "dropdown-item"%>
            <div class="dropdown-divider"></div>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, data: { confirm: "Are you sure?" }, class: "dropdown-item"%>
          </div>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Register", new_user_registration_path, class: "nav-link" %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagramark</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "layouts/navigation" %>
    <!-- Page Content -->
    <div class="contai1ner">
      <div class="row">
        <div class="col-lg-12 text-center">
            <br>
            <div class="flash mx-auto">
              <% flash.each do |key, value| %>
                <div class="alert alert-<%= key %> alert-dismissible">
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <strong><%= value %></strong> 
                </div>
              <% end %>
          </div>
          <%= yield %>
        </div>
      </div>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/posts/index.html.erb
<div id="post">
  <% @posts.each do |post| %>
    <div class="row">
      <figure class="figure mx-auto">
        <!-- <img src="..." class="figure-img img-fluid rounded" alt="A generic square placeholder image with rounded corners in a figure."> -->
        <%= link_to (image_tag post.image.url), post, class: "figure-img img-fluid rounded" %>
        <figcaption class="figure-caption text-left">
            <p><%= post.description %></p> 
            <small><%= link_to post.user.username ? post.user.username : post.user.email, user_path(post.user) %>, <%= time_ago_in_words(post.created_at) %> ago</small>
            <% if user_signed_in? && current_user == post.user %>
              <div id="btn-theme" class="float-right">
                <%= link_to "X", post, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-sm", style: "border-radius:50%; height: auto; margin-bottom: 10px; background-color:#aa9888; color: cornsilk; border: 0px;" %>
              </div>
            <% end %>
        </figcaption>
      </figure>
    </div>
   <% end %> 
</div>

app/views/posts/new.html.erb
<%= render 'layouts/error_messages', obj: @post %>

<div class="row">
  <div class="col-xs-12 mx-auto">
    <div id="form">
      <div class="panel panel-default mx-auto text-left">
        <div class="panel-heading">
           <h2>Share photo</h2>
        </div>
        <div class="panel-body">
          <%= form_for @post, html: { multipart: true } do |f| %>
            <div class="form-group">
              <%= f.label :image %>
              <%= f.file_field :image, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= f.label :description, value: "Caption" %>
              <%= f.text_area :description, class: "form-control" %>
            </div>
            <div id="btn-theme">
              <%= f.submit "Upload", class: "btn btn-outline-dark float-right" %>
            </div>
          <% end %>
        </div><br>
        <div class="panel-footer"> 
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div id="post">
  <figure class="figure">
    <%= image_tag(@post.image.url) %>
    <figcaption class="figure-caption text-left">
      <p><%= @post.description %></p> 
      <small><%= link_to @post.user.username ? @post.user.username : @post.user.email, user_path(@post.user) %>, <%= time_ago_in_words(@post.created_at) %> ago</small>
      <% if user_signed_in? && current_user == @post.user %>
        <div id="btn-theme" class="float-right">
          <%= link_to "X", post_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-sm", style: "border-radius:50%; height: auto; margin-bottom: 10px; background-color:#aa9888; color: cornsilk; border: 0px;" %>
        </div>
      <% end %>
      </figcaption>
  </figure>
</div>

app/views/users/_result.html.erb
<% if params[:action] == 'search' %>
  <div class="flash mx-auto">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %> alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong><%= value %></strong> 
      </div>
    <% end %>
  </div>
<% end %>

<% if @users %>
  <% if @users.size > 0 %>
    <div id="friend-lookup-results" class="well results-block col-md-12">

      <ul class="list-group">
        <% @users.each do |user| %>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            <div>
              <%= link_to gravatar_for(user, 300, "img-circle-link"), user_path(user) %>
              <% if user.username %>
                <%= link_to user.username, user_path(user) %>
              <% else %>
                <%= link_to user.email, user_path(user) %>
              <% end %>
            </div>
            <% if user_signed_in? && current_user %>
              <% if current_user.not_following_with?(user.id) %>
                <%= link_to "Follow", follow_user_path(user: current_user, following: user), class: "btn btn-sm btn-success", method: :post %>
              <% else %>
                <button class="btn btn-sm btn-primary" disabled>
                  Following
                </button>
              <% end %>
            <% end %>
          </li>
        <% end %>
      </ul>

    </div>
  <% end %>
<% end %>

app/views/users/_result.js.erb
// ajax rails 5 way
// hadling the rendering of the partial from result js erb
$('#results').html("<%= j (render 'users/result.html') %>")

app/views/users/find_people.html.erb
<div class="my-search">
  <div id="user-lookup" align="left">
    <%= form_tag search_users_path, remote: true, method: :get, id: "user-lookup-form" do %>
      <div class="row">
        <div class="col-sm-12">
          <h2>Find People</h2>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-9">
          <%= text_field_tag :search_param, params[:search_param], placeholder: "Enter username or email", autofocus: true, class: "form-control search-box input-lg" %>
        </div>
        <div class="col-sm-3">
          <%= button_tag(type: :submit, class: "btn btn-sm btn-success") do %>
            <i class="fa fa-search"></i> Search
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<br>

<div id="results">
  <%= render 'users/result' %>
</div>

app/views/users/following.html.erb
<% if @follows.size > 0 %>
  <ul class="list-group">
    <li class="list-group-item d-flex justify-content-between align-items-center"><h2>Following: <%= current_user.following.count %></h2>
    </li>
    <% @follows.each do |following| %>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <div>
          <%= link_to gravatar_for(following, 300, "img-circle-link"), user_path(following) %>
          <% if following.username %>
            <%= link_to following.username, user_path(following) %>
          <% else %>
            <%= link_to following.email, user_path(following) %>
          <% end %>
        </div>
      <%= link_to "Unfollow", follow_path(following), method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-sm btn-danger" %>
      </li>
    <% end %>
  </ul>
<% else %>
  <div class="row col-lg-12">
    <p class="lead mx-auto">You do not follow anyone! Please follow some users</p>
  </div>
<% end %>

app/views/users/index.html.erb
<h1 align="center">People</h1>
<div class="center">
  <% @users.each do |user| %>
    <ul class="listing">
      <div class="row">
        <div class="card card-body bg-transparent">
          <li><%= link_to gravatar_for(user, 300, "img-circle-link"), user_path(user), size: 300 %></li>
          <li class="article-title">
            <%= link_to user.email, user_path(user) %>
          </li>
          <!-- we want pluralize if the user has article/articles, and don't display if none -->
          <li><small><%= pluralize(user.posts.count, "photo") if user.posts %></small></li>
          <!-- delete user here not yet made the admin -->
        </div>
      </div>
    </ul>
  <% end %>
</div>

app/views/users/show.html.erb
<div class ="container my-profile">
  <div class="row">
    <div class="col-sm-6" align="right">
      <%= gravatar_for @user, 300, "img-circle" %>
    </div>
    <div class="col-sm-6" align="left">
      <h2><%= @user.username ? @user.username : @user.email %></h2>
      <% if user_signed_in? && current_user.not_follow_myself(@user) %>
        <% if current_user.not_following_with?(@user.id) %>
          <%= link_to "Follow", follow_user_path(user: current_user, following: @user), class: "btn btn-sm btn-success", method: :post %>
        <% else %>
          <%= link_to "Unfollow", follow_path(@user), method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-sm btn-danger" %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<h6 align="center"><%= @user.username ? @user.username : @user.email %>'s posts</h6>

<div id="post-profile" class="container">
    <div class="row">
    <% @user.posts.each do |post| %>
      <figure class="figure mx-auto">
        <%= link_to (image_tag post.image.url), post, class: "figure-img img-fluid rounded" %>
        <figcaption class="figure-caption text-left">
            <p><%= post.description %></p>
            <small><%= link_to post.user.username ? post.user.username : post.user.email, user_path(post.user) %>, <%= time_ago_in_words(post.created_at) %> ago</small>
            <% if user_signed_in? && current_user == post.user %>
              <div id="btn-theme" class="float-right">
                <%= link_to "X", post, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-sm", style: "border-radius:50%; height: auto; margin-bottom: 10px; background-color:#aa9888; color: cornsilk; border: 0px;" %>
              </div>
            <% end %>
        </figcaption>
      </figure>
    <% end %> 
    </div>
</div>